version: 2
jobs:
  build:
    docker:
      - image: php:7.2-fpm

    steps:
      - checkout

      - run: apt update
      - run: apt-get install -y zlib1g-dev libpq-dev git libicu-dev libxml2-dev \
            && docker-php-ext-configure intl \
            && docker-php-ext-install intl \
            && docker-php-ext-install zip xml
      - run: pecl install mongodb
      - run: echo "extension=mongodb.so" > $PHP_INI_DIR/conf.d/mongodb.ini

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: composer phpunit
      - run: composer phpcs
