version: '2'
services:
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ../:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
        links:
          - mongodb
          - elasticsearch
    nginx:
        build: nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
    mongodb:
        image: mongo:3
        ports:
          - "27018:27017"
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
        environment:
          - discovery.type=single-node
        ports:
          - 9200:9200
    kibana:
        image: docker.elastic.co/kibana/kibana:7.0.0
        ports:
          - 5601:5601
