version: '2'
services:
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ../:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
        links:
          - mongodb
    nginx:
        build: nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
    mongodb:
        image: mongo:3
        ports:
          - "27018:27017"
