Mutation:
    type: object
    config:
      fields:
        createAccount:
          type: AccountPayload!
          resolve: "@=mutation('createAccount', [args])"
          args:
            input:
              type: AccountInput!

AccountPayload:
  type: object
  config:
    fields:
      id:
        type: "String!"
      name:
        type: "String!"
      currency:
        type: "String!"

AccountInput:
  type: input-object
  config:
    fields:
      accountName:
        type: "String!"
        description: "Name of the account"
      accountCurrency:
        type: "String!"
        description: "Currency of the account"
