Query:
  type: object
  config:
    description: "Accounts repository"
    fields:
      account:
        type: "Account"
        args:
          id:
            description: "Resolves using the account id."
            type: "String"
        resolve: "@=resolver('Account', [args])"
