Query:
  type: object
  config:
    description: "Accounts repository"
    fields:
      account:
        type: "Account"
        args:
          id:
            description: "Resolves using the account id."
            type: "String"
        resolve: "@=resolver('Account', [args])"
Account:
  type: object
  config:
    description: "An account"
    fields:
      id:
        type: "String!"
        description: "The unique ID of the account."
      name:
        type: "String"
        description: "Name of the account"
      currency:
        type: "String"
        description: "Currency of the account"
      balance:
        type: "Float"
        description: "Balance of the account"
