# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    mongodb_uri: '%env(BROADWAY_EVENT_STORE_MONGODB_URI)%'
    mongodb_database: '%env(BROADWAY_EVENT_STORE_MONGODB_DATABASE)%'
    elasticsearch:
        hosts:
            - elk:9200

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # cqrs
    Broadway\CommandHandling\CommandBus: '@broadway.command_handling.simple_command_bus'

    # command handlers
    App\Account\Application\AccountCommandHandler:
        tags:
            - { name: broadway.command_handler }

    # event sourcing
    Broadway\EventHandling\EventBus: '@broadway.event_handling.event_bus'
    Broadway\EventStore\EventStore: '@broadway.event_store.mongodb'
    App\Account\Domain\AccountRepository: '@App\Account\Infrastructure\AccountEventStoreRepository'

    # projectors
    App\Account\Domain\ReadModel\AccountDetailsProjector:
        arguments:
            $accountDetailsRepository: '@App\Account\Domain\ReadModel\AccountDetailsRepository'
        tags: [ broadway.domain.event_listener ]

    # read model repository
    App\Account\Domain\ReadModel\AccountDetailsRepository:
        class: 'Broadway\ReadModel\ReadModel'
        factory: ['@broadway.read_model.elasticsearch.repository_factory', create]
        arguments:
            - 'symfsavings.account_details'
            - 'App\Account\Domain\ReadModel\AccountDetails'

    App\RestApi\TestCommand:
        arguments:
            - '@Broadway\CommandHandling\CommandBus'
            - '@App\Account\Domain\ReadModel\AccountDetailsRepository'
        tags:
            - { name: 'console.command', command: 'app:create-account' }
